spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
libraryapp.rabbitmq.queue=libraryapp.queue2
libraryapp.rabbitmq.exchange=libraryapp.direct
libraryapp.rabbitmq.routingkey1=libraryapp.routingkey1